name = "hooks"
main = "index.js"
compatibility_date = "2024-09-28"

workers_dev = false
send_metrics = false

# Force enable keeping logs
[observability]
enabled = true

[[durable_objects]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
script_name = "index"
